### ISSUE TITLE
시간나면 고치면 좋을 것들 모음

### ISSUE THREAD

**Issue by bebusl** [wanted-pre-onboarding-fe-8/8dmin#25]
## 1. 화면 가로폭 줄어들면 검색/엑셀다운로드 버튼 높이가 늘어남
![image](https://user-images.githubusercontent.com/49019236/181141656-bb7a0c51-3a39-4e40-8246-1a9a3ef4deab.png)

## 2. 거주지 검색할 때 검색어에 스페이스바 있으면 검색 아예 안 됨
![image](https://user-images.githubusercontent.com/49019236/181142092-cb527afa-d046-47cf-88b6-e829d5d70c25.png)
띄어쓰기 없을 때
![image](https://user-images.githubusercontent.com/49019236/181142244-aa6f84e6-3b80-4131-87e1-70769a6336fe.png)
띄어쓰기 있을 때

**Comment by bebusl** [comment]
## 2번 해결책. 셀렉터 로직 변경
keyword = '서울 광진구'라고 가정

```
case SELECT_REGION: {
            const splitKeyword = keyword.split(' '); //검색어 공백단위로 끊어 리스트로 만듦. 공백이 없으면 그냥 [keyword]형태로 만들어짐
            const selectedRegion = applicantState.filter((candidate) => {
              const integrated = candidate.region.replace(' ', ''); //서울 광진구 => 서울광진구
              return splitKeyword.every((kwd) => integrated.includes(kwd));=>서울광진구에서 모든 검색어가 포함되어 있으면 true 반환
            });
            return selectedRegion;
}
```

**Comment by taetaeo** [comment]
아 그렇네요.. 감사합니다

**Comment by sunaerocket** [comment]
부라보~
